version: '3.7'

services:
  db:
    image: postgres:13.4
    environment:
      POSTGRES_DB: otus_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgsql_Password
    ports:
      - "5450:5432"
    volumes:
      - orus_db:/var/lib/postgresql/data:rw

volumes:
  orus_db:
