version: '3.7'

services:
  db:
    image: postgres:13.4
    environment:
      POSTGRES_DB: otus_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgsql_Password
    ports:
      - "5450:5432"
    volumes:
      - otus_db:/var/lib/postgresql/data:rw
      - otus_db_ts_films:/var/lib/postgresql/tspace_films:rw

volumes:
  otus_db:
  otus_db_ts_films:
